/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppCheckoutRouteImport } from './routes/app/checkout'
import { Route as AppCrmRouteImport } from './routes/app/crm'
import { Route as AppFilesRouteImport } from './routes/app/files'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppNotesRouteImport } from './routes/app/notes'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTimeRouteImport } from './routes/app/time'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/crm': typeof AppCrmRoute
  '/app/files': typeof AppFilesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/time': typeof AppTimeRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/crm': typeof AppCrmRoute
  '/app/files': typeof AppFilesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/time': typeof AppTimeRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/crm': typeof AppCrmRoute
  '/app/files': typeof AppFilesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/time': typeof AppTimeRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/assistant'
    | '/app/checkout'
    | '/app/crm'
    | '/app/files'
    | '/app/invoices'
    | '/app/notes'
    | '/app/projects'
    | '/app/settings'
    | '/app/time'
    | '/app/'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/app/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/assistant'
    | '/app/checkout'
    | '/app/crm'
    | '/app/files'
    | '/app/invoices'
    | '/app/notes'
    | '/app/projects'
    | '/app/settings'
    | '/app/time'
    | '/app'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/app/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/assistant'
    | '/app/checkout'
    | '/app/crm'
    | '/app/files'
    | '/app/invoices'
    | '/app/notes'
    | '/app/projects'
    | '/app/settings'
    | '/app/time'
    | '/app/'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/app/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/time': {
      id: '/app/time'
      path: '/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppCrmRoute: typeof AppCrmRoute
  AppFilesRoute: typeof AppFilesRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimeRoute: typeof AppTimeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppCrmRoute: AppCrmRoute,
  AppFilesRoute: AppFilesRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppNotesRoute: AppNotesRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTimeRoute: AppTimeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
